### ISSUE TITLE
Completar datos de prueba

### ISSUE THREAD

**Issue by alvarosaco** [consumo-colaborativo/compart.io-2015#1]
He añadido algunos datos de prueba y he hecho un MERGE en DEVELOP para incluir los archivos .json de /schema/data/. 

¿Qué tal lo ves @msanchezmora? Ah! He visto que además de la tabla/collection "compartiocategories" hay otra que se llama "categories". ¿A qué hace referencia esta última?

**Comment by msanchezmora** [comment]
Estupendo!
Si consultas la definición de la tabla verás que la tabla "category" pertenece al módulo dry-login.

**Comment by alvarosaco** [comment]
Genial. Gracias @msanchezmora : )
